### ISSUE TITLE
Access undock() POCO javascript

### ISSUE THREAD

**Issue by aesalazar** [HadoukenIO/layouts-service#11]
Hi guys.  I was checking out the demo app and trying my hand at creating my own.

Say I wanted to create a simple windows using fin.desktop.Window to instantiate new one with simply HTML and JS.  How would I get to the undock command from there?  Can I do it through the fin object somehow?

Thanks
Ernie

**Comment by dcchuck** [comment]
Hey Ernie,

You can import the client side library from NPM

https://www.npmjs.com/package/openfin-layouts

Cheers,

Chuck Danielsson

**Comment by aesalazar** [comment]
Thanks Chuck.  I am using Browserify to bing in the node module into the html's javascript.  Generally, it works but I every couple of restarts of the app I get this in the console:

`Uncaught (in promise) Error: Window {"isTrusted":true} does not exist`

It happens when the Undock command is called.  Sometimes the windows are able to dock (and the drag-opacity works) and sometimes nothing works at all.  have you seen that before?

Thanks
Ernie

**Comment by espenove** [comment]
Hi Ernie,

We have not seen this before, are you able to provide us with a gist/repo with code where you can reproduce the error, so we can look into?

Regards,
Espen

**Comment by tgoc99** [comment]
@aesalazar, Yes, it could be due to the internet service. When you put layouts in an app manifest as a service, it will need to retrieve the service manifest/assets from our server.  If it cannot, the service will not start and the promise in your demo where you create the undock function will never resolve.

**Comment by aesalazar** [comment]
@tgoc99  Ok, thanks for the help.  I was thinking that the api was cached with the runtime but what you describe makes sense.
