### ISSUE TITLE
Window remains transparent when dragged to top of screen.

### ISSUE THREAD

**Issue by AndySmithSL** [HadoukenIO/layouts-service#203]
Scott Logic have developed an application called Stockflux that uses the OpenFin HTML5 container. We're currently carryout work on this application to improve and update it and have noticed some issues we believe may be Openfin issues.

When you drag a window (by the toolbar) to the top of the screen in order to maximise it, the window maximises / docks to the full screen however it remains transparent.

To replicate:
- Drag a window by the taskbar to the top of the screen (as if you were maximising it in your display).
- The dragging process on a window changes the opacity of the window and the window becomes transparent (as expected).
- When the window is maximised at the top of the screen and the taskbar is released, the window remains transparent.

Expected behaviour:
- We would expect the window to revert to normal opacity once it is maximised at the top of the screen and the taskbar is released.

![image](https://user-images.githubusercontent.com/42347047/49865427-d0b66380-fdfc-11e8-92c3-313ec589b3c8.png)

Other details:
Operating System => Windows 10
Openfin-layouts => 0.9.3
Node => v11.4.0 (also occurred on 11.3.0)
OpenFin Runtime => 9.61.36.36

**Comment by AndySmithSL** [comment]
See following Scott Logic Issue:
https://github.com/ScottLogic/StockFlux/issues/997

**Comment by espenove** [comment]
Thanks Andy, noted - we're looking into it

**Comment by tgoc99** [comment]
Fixed as of v0.9.6
