### ISSUE TITLE
Maximised window border incomplete / partially missing.

### ISSUE THREAD

**Issue by AndySmithSL** [HadoukenIO/layouts-service#204]
Scott Logic have developed an application called Stockflux that uses the OpenFin HTML5 container. We're currently carryout work on this application to improve and update it and have noticed some issues we believe may be Openfin issues.

When maximising a window by dragging the toolbar to the top of the screen, once the window docks to the entire screen, a thick white border appears around the edge of the screen. However this border is missing or incomplete at certain parts of the screen.

To replicate:
- Drag the window to the top of the screen in order to maximise the window.
- Once the window is docked to the entire screen, an incomplete thick white border appears.

Expected behaviour:
- We would expect the thick white border to fully surround the entire edge of the screen.

![stockflux border](https://user-images.githubusercontent.com/42347047/49867012-2260ed00-fe01-11e8-9d8c-bde167682e27.png)

Other details:
Operating System => Windows 10
Openfin-layouts => 0.9.3
Node => v11.4.0 (also occurred on 11.3.0)
OpenFin Runtime => 9.61.36.36

This issue may be linked to issue #203 opened by Scott Logic as well. Can you confirm if these issues are indeed a defect in the latest Openfin layout? Thanks.

**Comment by AndySmithSL** [comment]
See following Scott Logic Issue:
https://github.com/ScottLogic/StockFlux/issues/998

**Comment by espenove** [comment]
Thanks Andy, noted - we're looking into it

**Comment by tgoc99** [comment]
Andy - I was able to replicate this on your application without layouts service running.  I believe the issue may be unrelated to the layouts service.  Please re-open if you confirm that this only happens with layouts or contact support@openfin.co for OpenFin runtime support if you are continuing to see issues.
