### ISSUE TITLE
Window-Snap drop shadow hidden underneath other applications

### ISSUE THREAD

**Issue by chriswilty** [HadoukenIO/layouts-service#205]
When dragging an openfin window to snap to / group with another, a drop-shadow indicates where the dragged window will be docked against the other.

If there is another (non-OpenFin) application open on the desktop, this drop-shadow appears underneath that application window, which _may_ result in the drop-shadow being completely hidden if the application window is larger than the drop-shadow. I would expect the drop-shadow to appear beneath the OpenFin window being dragged, but above all others on the desktop.

In the image below, a large-sized OpenFin window on the left is being dragged to dock against a smaller OpenFin window on the right. There is a Notepad++ application window visible beneath. The snap shadow that shows where the dragged window will dock is _beneath_ the Notepad++ window.

![49384224-75a4b280-f712-11e8-8584-29b072a729e9](https://user-images.githubusercontent.com/15246391/49875061-fdc43f80-fe17-11e8-9553-6dc61637cb37.png)

OS: Windows 10, intel x64 processor
Node: 10.14.1
OpenFin Runtime: 9.61.36.36
OpenFin Layouts Service: 0.9.3

**Comment by espenove** [comment]
Hi Chris, thanks for feedback. This issue is fixed in 0,9.4, scheduled to come out soon

**Comment by tgoc99** [comment]
Closed due to fix in v0.9.4.
